name: voice_ai_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  model_viewer_plus: ^1.9.2
  cupertino_icons: ^1.0.8
  saudi_riyal_symbol: ^0.0.7
  pulsator: ^1.0.0+2
  speech_to_text: ^6.6.0
  supabase_flutter: ^2.9.1
  flutter_sound: ^9.28.0
  permission_handler: ^10.0.0
  mime: ^2.0.0
  uuid: ^4.5.1
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/riyalsymbol.png
    - assets/Mada_Logo.png
    - assets/9719797.psd
    - assets/9720042.jpg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/mainIcon.png"
  adaptive_icon_background: "#ffffff"
  # adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
